### ISSUE TITLE
Test configuration with backup and resize/reduce causes tests to fail

### ISSUE THREAD

**Issue by arfsb** [ysugimoto/aws-lambda-image#129] opened 2017-03-23 15:57 UTC
We wanted to add an end-to-end test that included a backup and reduce/resize.  However, running `npm test` would intermittently fail (occasionally the first time running the test will pass but subsequent runs will fail).

_**NOTE: This seems to only affect tests.  Using backup and reduce/resize on Lambda seems to work ok.**_

The test was added as the last test in `e2e-jpeg.js`:
<pre>
test("Backup and reduce JPEG with suffix", async t => {
    await processor.run(new Config({
        backup: {
            suffix: "_backup"
        },
        "reduce": {
            "suffix": "_reduced"
        }

    }));
    t.is(images.length, 2);
    const fixture = await fsP.readFile(`${__dirname}/fixture/fixture.jpg`);

    const backupImage = images.shift();
    t.is(backupImage.fileName, "HappyFace_backup.jpg");
    t.true(backupImage.data.length === fixture.length);

    const image = images.shift();
    t.is(image.fileName, "HappyFace_reduced.jpg");
    t.true(image.data.length > 0);
    t.true(image.data.length < fixture.length);
});
</pre>

The output:
<pre>
  76 passed
  4 failed

  e2e-jpeg › Resize JPEG with quality
  /usr/local/tixr/workspace/Image-Processor/test/e2e-jpeg.js:105

   104:     }));                         
   105:     t.is(images.length, 1);      
   106:     const image = images.shift();

  Actual:

    2

  Expected:

    1

  Test.<anonymous> (test/e2e-jpeg.js:105:7)
  step (test/e2e-jpeg.js:6:191)

  e2e-jpeg › Reduce JPEG with basic configuration
  /usr/local/tixr/workspace/Image-Processor/test/e2e-jpeg.js:56

   55:     }));                         
   56:     t.is(images.length, 1);      
   57:     const image = images.shift();

  Actual:

    2

  Expected:

    1

  Test.<anonymous> (test/e2e-jpeg.js:56:7)
  step (test/e2e-jpeg.js:6:191)

  e2e-jpeg › Reduce JPEG with bucket/directory configuration
  /usr/local/tixr/workspace/Image-Processor/test/e2e-jpeg.js:72

   71:     }));                         
   72:     t.is(images.length, 1);      
   73:     const image = images.shift();

  Actual:

    2

  Expected:

    1

  Test.<anonymous> (test/e2e-jpeg.js:72:7)
  step (test/e2e-jpeg.js:6:191)

  e2e-jpeg › Backup and reduce JPEG with suffix
  /usr/local/tixr/workspace/Image-Processor/test/e2e-jpeg.js:151

   150:     const backupImage = images.shift();                
   151:     t.is(backupImage.fileName, "HappyFace_backup.jpg");
   152:     t.true(backupImage.data.length === fixture.length);

  Difference:

  "some/HappyFace_backup.jpg"

  Test.<anonymous> (test/e2e-jpeg.js:151:7)
  step (test/e2e-jpeg.js:6:191)
</pre>

**Comment by kdybicz** [comment] 2017-03-27 06:41
Thanks for raising, but it's a duplicate of #113

**Closed by kdybicz** 2017-03-27 06:41 UTC
